// SoundTable: SNDTBL_DEMO
#define SND_Access_denied            1
#define SND_Access_granted           2
#define SND_Hello                    3
#define SND_Please_repeat            4
#define SND_Please_say_your_password 5
#define SND_Hello_give_command       6
#define SND_Please_say_name          7
#define SND_Pwd_activated            8
// Grammar: trig_demo
#define WS4_HELLO_DEVICE             0
// Grammar: comm_demo
#define WS5_PASSWORD_SETUP           0
#define WS5_PASSWORD_ACTIVATED       1
#define WS5_CURTAIN_UP               2
#define WS5_CURTAIN_DOWN             3
#define WS5_LIGHTS_ON                4
#define WS5_LIGHTS_OFF               5